### ISSUE TITLE
Feature:  Template default.bginfo file - allowing for arbitrary data

### ISSUE THREAD

**Issue by brettswift** [ncorrare/bginfo#1]
Great to see this module exists with active work happening on it!

I'd like to throw out a feature request as it would benefit us.   We might not be able to tackle this for a couple months but if it's not picked up by then we might be able to.

The use case is that we have some meta data about servers in hiera, and potentially facts.   We would like this displayed when someone logs in. (Server ownership for example, which may change as it gets re-assigned). 

The ability to have key/value pairs would be good.  But ultimately if we could supply our own template, and our own hash of data, that might be the most versatile implementation. 

What do you think ?

**Comment by ncorrare** [comment]
Hey @brettswift . I've been thinking about it for a while now
The issue here is that the bgi files are encoded in a weird way, and I'm afraid templating them might break it. In any case... It's just ugly to template files that aren't really text, but I'll give it a shot anyway.

I'm going to try a small PR enabling to change the background file to an arbitrary path and we'll see.

**Comment by ncorrare** [comment]
Hey Brett,
After spelunking into the file with a hex editor, I honestly have to come to the conclusion that templating it and inserting arbitrary stuff there is not a good idea. It has a proprietary header, so I have to conclude it's a binary with strings.

I'm researching if we can model around the bginfo binary to automatically create the file and model around that.

**Comment by brettswift** [comment]
Cool thanks.  Our windows activities have been put on hold for a while.. not sure when they'll be picked up again. 

Anyways let me know if you come up with something here.  When we pick up windows configuration efforts again I will test it out!

**Comment by ncorrare** [comment]
Unless someone has a bit more insight on how bginfo creates/reads it's config file, I'm closing this with a [WON'T FIX] for the time being.
